steps:
  # Create the .env file
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "TYPESENSE_API_TOKEN=${_TYPESENSE_API_TOKEN}" > .env.production && \
        echo "GOOGLE_ANALYTICS_ID=G-45RJFY1NNG" >> .env.production && \
        echo "API_ROOT_URL=https://staging.busca.dados.rio" >> .env.production && \
        echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=6Le9BwgrAAAAAFsZHFHdv-JWZApR-x-9ZOVnnetv" >> .env.production
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/buscador-rio:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/buscador-rio:$COMMIT_SHA"]
  # Kustomize: set the image in the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/staging"
    entrypoint: "kustomize"
    args:
      - "edit"
      - "set"
      - "image"
      - "gcr.io/project-id/buscador-rio=gcr.io/$PROJECT_ID/buscador-rio:$COMMIT_SHA"
  # Kustomize: apply the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/staging"
    entrypoint: "kustomize"
    args: ["build", ".", "-o", "staging.yaml"]
  # Deploy the application to the GKE cluster
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/staging"
    args:
      - "run"
      - "--filename=staging.yaml"
      - "--location=us-central1"
      - "--cluster=datario"
      - "--project=datario"

images:
  - "gcr.io/$PROJECT_ID/buscador-rio:$COMMIT_SHA"